### PR TITLE
Using namespace literals

### PR DESCRIPTION
**Pull request by tkruse**

### CODE REVIEW

**Comment by tkruse** [comment]
manually merged

**Comment by tkruse** [comment]
Given the response on https://github.com/google/styleguide/pull/92, I wonder fi we should revert this change, or treat it differently. @mattyclarkson, possibly literal namespaces could be guarded by a different rule, so you could switch off checking of literal namespaces, but keep the checks of other namespaces. What do you think?

**Comment by tkruse** [comment]
Created https://github.com/tkruse/cpplint/pull/28 for redesigning

**Comment by mattyclarkson** [comment]
@tkruse, sure. It would make sense to have it under a seperate rule.

**Pull request closed without merging**
